// This file is auto-generated by the AI Schema Architect.
import companylogo from './documents/companylogo'
import ctasection from './objects/ctasection'
import featureitem from './documents/featureitem'
import featuressection from './objects/featuressection'
import footer from './documents/footer'
import footerlink from './documents/footerlink'
import footerlinkcolumn from './documents/footerlinkcolumn'
import header from './documents/header'
import herosection from './objects/herosection'
import metricitem from './documents/metricitem'
import metricssection from './objects/metricssection'
import page from './documents/page'
import quotesection from './objects/quotesection'
import siteSettings from './documents/site-settings'
import socialproofsection from './objects/socialproofsection'

export const schemaTypes = [
  companylogo,
  ctasection,
  featureitem,
  featuressection,
  footer,
  footerlink,
  footerlinkcolumn,
  header,
  herosection,
  metricitem,
  metricssection,
  page,
  quotesection,
  siteSettings,
  socialproofsection,
];
